name: CI

on:
  push:
    tags:
      - "*.*.*"
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          npm install
          npm run production
